-- V12: Social notifications (follow + share-to-followers feed).
-- Postgres/prod only — the H2 dev profile builds its schema from JPA entities.
-- See issue #175 follow-up. Additive: existing users default to notifications enabled.

-- ── Per-user master switch ──────────────────────────────────────────────────
-- When false, no follow/share notifications are generated for this user.
ALTER TABLE users
    ADD COLUMN social_notifications_enabled boolean NOT NULL DEFAULT true;

-- ── Notification feed ───────────────────────────────────────────────────────
-- Online-only (never synced to Room). One row per (recipient, event).
CREATE TABLE notifications (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_uid     varchar(255) NOT NULL,   -- who sees this notification
    actor_uid         varchar(255) NOT NULL,   -- who caused it (follower / sharer)
    type              varchar(16)  NOT NULL,   -- FOLLOW | SHARE
    subject_kind      varchar(16),             -- DIET | MEAL | WORKOUT (null for FOLLOW)
    subject_server_id uuid,                    -- shared item id (null for FOLLOW)
    subject_name      varchar(200),            -- denormalised item name at share time
    created_at        timestamptz  NOT NULL DEFAULT now(),
    read_at           timestamptz              -- null until the recipient reads it
);

-- Feed query: a user's notifications newest-first, and unread count.
CREATE INDEX idx_notifications_recipient ON notifications (recipient_uid, created_at DESC);
