-- V15: planned meals — assign individual meals to a day plan's slots, independent of a diet.
-- Postgres/prod only (H2 dev builds its schema from JPA entities). A day can have a diet AND/OR
-- loose planned meals; the dashboard merges both by slot. Mirrors planned_workouts.
CREATE TABLE planned_meals (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_plan_id bigint       NOT NULL,
    meal_id     bigint       NOT NULL,
    slot        varchar(50)  NOT NULL
);
CREATE INDEX idx_planned_meals_day_plan_id ON planned_meals (day_plan_id);
