-- Web Push subscriptions for the PWA (webapp). Each row is one browser/device subscription that
-- opted in to "you haven't logged yet" reminders. The scheduler (GitHub Actions cron → the internal
-- reminders endpoint) sends a push to these when the user hasn't logged today.
--   endpoint            : the push-service URL, unique per browser subscription (the natural key).
--   p256dh / auth       : the subscription's encryption keys (from PushManager.subscribe).
-- Presence of a row = reminders enabled for that device; unsubscribe deletes it.
-- Identity + CURRENT_TIMESTAMP are used (not a pg_dump sequence) so this runs on both Neon Postgres
-- and the H2 (PostgreSQL mode) used by local/dev + tests.
CREATE TABLE public.push_subscriptions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid  character varying(255)  NOT NULL,
    endpoint      character varying(2048) NOT NULL,
    p256dh        character varying(255)  NOT NULL,
    auth          character varying(255)  NOT NULL,
    user_agent    character varying(256),
    created_at    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at  timestamp with time zone,
    CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_subscriptions_uid ON public.push_subscriptions (firebase_uid);
