-- In-app user feedback submissions (not part of the sync contract).
CREATE TABLE feedback (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid TEXT        NOT NULL,
    message      TEXT        NOT NULL,
    app_version  TEXT,
    platform     TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_feedback_uid_created ON feedback (firebase_uid, created_at DESC);
