-- V9: Social foundation (follow graph, profiles, shareable templates, safety).
-- Postgres/prod only — the H2 dev profile builds its schema from JPA entities.
-- See GitHub issue #175. This migration is additive; existing sync behaviour is
-- untouched (all new template columns default to non-shared / no-provenance).

CREATE EXTENSION IF NOT EXISTS citext;   -- case-insensitive unique handles
CREATE EXTENSION IF NOT EXISTS pg_trgm;  -- fast ILIKE search on display_name

-- ── Profile fields on users ─────────────────────────────────────────────────
-- handle is nullable until the user claims one; format enforced app-side
-- (^[a-z0-9_]{3,20}$). citext gives case-insensitive uniqueness for free.
ALTER TABLE users
    ADD COLUMN handle        citext UNIQUE,
    ADD COLUMN bio           varchar(300),
    ADD COLUMN avatar_seed   varchar(64),
    ADD COLUMN is_searchable boolean NOT NULL DEFAULT true;

-- Substring search on display_name; handle prefix search is served by the
-- citext UNIQUE btree above.
CREATE INDEX idx_users_displayname_trgm ON users USING gin (display_name gin_trgm_ops);

-- ── Follow graph ────────────────────────────────────────────────────────────
CREATE TABLE follows (
    follower_uid varchar(255) NOT NULL,   -- who is following
    followee_uid varchar(255) NOT NULL,   -- who is being followed
    created_at   timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (follower_uid, followee_uid),
    CHECK (follower_uid <> followee_uid)
);
CREATE INDEX idx_follows_followee ON follows (followee_uid);  -- "my followers"
CREATE INDEX idx_follows_follower ON follows (follower_uid);  -- "who I follow"

-- ── Blocks ──────────────────────────────────────────────────────────────────
CREATE TABLE blocks (
    blocker_uid varchar(255) NOT NULL,
    blocked_uid varchar(255) NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (blocker_uid, blocked_uid),
    CHECK (blocker_uid <> blocked_uid)
);
CREATE INDEX idx_blocks_blocked ON blocks (blocked_uid);      -- "who blocked me"

-- ── Content reports (moderation queue) ──────────────────────────────────────
CREATE TABLE content_reports (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_uid     varchar(255) NOT NULL,
    entity_type      varchar(32)  NOT NULL,   -- DIET | MEAL | WORKOUT_TEMPLATE | USER
    entity_server_id uuid,                    -- null when entity_type = USER
    reported_uid     varchar(255),            -- author / reported user
    reason           varchar(64),
    detail           varchar(1000),
    created_at       timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_content_reports_created ON content_reports (created_at DESC);

-- ── Shareable templates ─────────────────────────────────────────────────────
-- Per-item share toggle (default private). Only templates are ever shareable.
ALTER TABLE diets             ADD COLUMN is_shared boolean NOT NULL DEFAULT false;
ALTER TABLE meals             ADD COLUMN is_shared boolean NOT NULL DEFAULT false;
ALTER TABLE workout_templates ADD COLUMN is_shared boolean NOT NULL DEFAULT false;

-- Provenance stamped by the copy engine (P1). Containers AND dedupe-able leaves.
ALTER TABLE diets             ADD COLUMN copied_from_uid varchar(255), ADD COLUMN copied_from_server_id uuid;
ALTER TABLE meals             ADD COLUMN copied_from_uid varchar(255), ADD COLUMN copied_from_server_id uuid;
ALTER TABLE workout_templates ADD COLUMN copied_from_uid varchar(255), ADD COLUMN copied_from_server_id uuid;
ALTER TABLE foods             ADD COLUMN copied_from_uid varchar(255), ADD COLUMN copied_from_server_id uuid;
ALTER TABLE exercises         ADD COLUMN copied_from_uid varchar(255), ADD COLUMN copied_from_server_id uuid;
