/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user profile. Auto-creates the user on first call.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List foods
         * @description Returns all system foods plus foods created by the authenticated user.
         */
        get: operations["listFoods"];
        put?: never;
        /** Create food */
        post: operations["createFood"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get food by ID */
        get: operations["getFood"];
        put?: never;
        post?: never;
        /** Delete food */
        delete: operations["deleteFood"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List meals
         * @description Returns all meals owned by the authenticated user.
         */
        get: operations["listMeals"];
        put?: never;
        /** Create meal */
        post: operations["createMeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meal by ID */
        get: operations["getMeal"];
        put?: never;
        post?: never;
        /** Delete meal */
        delete: operations["deleteMeal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List diets */
        get: operations["listDiets"];
        put?: never;
        /** Create diet */
        post: operations["createDiet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get diet by ID */
        get: operations["getDiet"];
        put?: never;
        post?: never;
        /** Delete diet */
        delete: operations["deleteDiet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grocery-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grocery lists */
        get: operations["listGroceryLists"];
        put?: never;
        /** Create grocery list */
        post: operations["createGroceryList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grocery-lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get grocery list by ID */
        get: operations["getGroceryList"];
        put?: never;
        post?: never;
        /** Delete grocery list */
        delete: operations["deleteGroceryList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List health metrics */
        get: operations["listHealthMetrics"];
        put?: never;
        /** Create health metric */
        post: operations["createHealthMetric"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-metrics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete health metric */
        delete: operations["deleteHealthMetric"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-metrics/custom-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List custom metric types */
        get: operations["listCustomMetricTypes"];
        put?: never;
        /** Create custom metric type */
        post: operations["createCustomMetricType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List daily logs */
        get: operations["listDailyLogs"];
        put?: never;
        /** Create or update daily log */
        post: operations["createDailyLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily log by ID */
        get: operations["getDailyLog"];
        put?: never;
        post?: never;
        /** Delete daily log */
        delete: operations["deleteDailyLog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull changes since timestamp
         * @description Returns all user-owned records with `updatedAt > since` across every domain.
         *     Android `SyncWorker` stores the `serverTime` from the previous response and passes it
         *     as `since` on the next call. On first sync, pass `since=1970-01-01T00:00:00Z`.
         */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push local changes to server
         * @description Upserts records by `serverId` using last-write-wins on `updatedAt`.
         *     Any domain list may be empty — send only what has changed locally.
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponse: {
            /** Format: int64 */
            id: number;
            firebaseUid: string;
            email?: string | null;
            displayName?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description A food item with per-100g macros. `isSystemFood=true` items are shared across all users
         *     and are never deleted during re-seed. `serverId` is the cross-device identity.
         */
        FoodDto: {
            /**
             * Format: int64
             * @description Server-assigned DB ID (omit on create)
             */
            id?: number;
            /**
             * Format: uuid
             * @description Stable client-generated UUID — sync identity
             */
            serverId?: string;
            name: string;
            brand?: string | null;
            barcode?: string | null;
            /** Format: double */
            caloriesPer100: number;
            /** Format: double */
            proteinPer100: number;
            /** Format: double */
            carbsPer100: number;
            /** Format: double */
            fatPer100: number;
            /** Format: double */
            gramsPerPiece?: number | null;
            /** Format: double */
            gramsPerCup?: number | null;
            /** Format: double */
            gramsPerTbsp?: number | null;
            /** Format: double */
            gramsPerTsp?: number | null;
            glycemicIndex?: number | null;
            /** @default false */
            isSystemFood: boolean;
            /** @default false */
            isFavorite: boolean;
            /**
             * Format: date-time
             * @description Last-modified instant (server-set; used for sync conflict resolution)
             */
            readonly updatedAt?: string;
        };
        MealFoodItemDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            mealId?: number;
            /** Format: int64 */
            foodId: number;
            /** Format: double */
            quantity: number;
            /**
             * @default GRAM
             * @enum {string}
             */
            unit: "GRAM" | "ML" | "PIECE" | "CUP" | "TBSP" | "TSP";
            notes?: string | null;
        };
        /** @description A named collection of foods assigned to a meal slot. */
        MealDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description Stable client-generated UUID — sync identity
             */
            serverId?: string;
            /** @description Owner — set by server from JWT; ignored on inbound requests */
            readonly firebaseUid?: string;
            name: string;
            /**
             * @default Lunch
             * @enum {string}
             */
            slot: "Breakfast" | "Lunch" | "Dinner" | "Snack";
            items?: components["schemas"]["MealFoodItemDto"][];
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        DietMealDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            dietId?: number;
            /** Format: int64 */
            mealId: number;
            /** @description 1=Mon…7=Sun; 0=any day */
            dayOfWeek: number;
            /**
             * @default Lunch
             * @enum {string}
             */
            slot: "Breakfast" | "Lunch" | "Dinner" | "Snack";
            instructions?: string | null;
        };
        /** @description A weekly diet template composed of meals, with optional macro targets. */
        DietDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description Stable client-generated UUID — sync identity
             */
            serverId?: string;
            readonly firebaseUid?: string;
            name: string;
            description?: string | null;
            /** Format: double */
            targetCalories?: number | null;
            /** Format: double */
            targetProtein?: number | null;
            /** Format: double */
            targetCarbs?: number | null;
            /** Format: double */
            targetFat?: number | null;
            meals?: components["schemas"]["DietMealDto"][];
            tagIds?: number[];
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        GroceryItemDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            groceryListId?: number;
            /**
             * Format: int64
             * @description Optional link to a Food record
             */
            foodId?: number | null;
            name: string;
            /**
             * Format: double
             * @default 1
             */
            quantity: number;
            /**
             * @default GRAM
             * @enum {string}
             */
            unit: "GRAM" | "ML" | "PIECE" | "CUP" | "TBSP" | "TSP";
            category?: string | null;
            /** @default false */
            done: boolean;
        };
        GroceryListDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description Stable client-generated UUID — sync identity
             */
            serverId?: string;
            readonly firebaseUid?: string;
            name: string;
            /**
             * Format: int64
             * @description Optional diet this list was generated from
             */
            dietId?: number | null;
            items?: components["schemas"]["GroceryItemDto"][];
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        /**
         * @description A single health measurement. Common `type` values: WEIGHT, STEPS, BLOOD_PRESSURE,
         *     HEART_RATE, SLEEP_HOURS, WATER_ML, BODY_FAT_PCT.
         *     For BLOOD_PRESSURE, use `subType=SYSTOLIC` / `DIASTOLIC` with `secondaryValue`.
         */
        HealthMetricDto: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            serverId?: string;
            readonly firebaseUid?: string;
            /** @example WEIGHT */
            type: string;
            /** @example SYSTOLIC */
            subType?: string | null;
            /** Format: double */
            value: number;
            /**
             * Format: double
             * @description Second reading (e.g. diastolic BP)
             */
            secondaryValue?: number | null;
            /** @example kg */
            unit: string;
            /**
             * Format: date-time
             * @description When the measurement was taken (client-provided)
             */
            recordedAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        /** @description User-defined metric type (e.g. "Waist circumference"). */
        CustomMetricTypeDto: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            serverId?: string;
            readonly firebaseUid?: string;
            name: string;
            unit: string;
            icon?: string | null;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        LoggedFoodDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            dailyLogId?: number;
            /** Format: int64 */
            foodId: number;
            /**
             * @default Lunch
             * @enum {string}
             */
            mealSlot: "Breakfast" | "Lunch" | "Dinner" | "Snack";
            /** Format: double */
            quantity: number;
            /**
             * @default GRAM
             * @enum {string}
             */
            unit: "GRAM" | "ML" | "PIECE" | "CUP" | "TBSP" | "TSP";
        };
        /** @description One day's food consumption log. One record per user per date. */
        DailyLogDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description Stable client-generated UUID — sync identity
             */
            serverId?: string;
            readonly firebaseUid?: string;
            /**
             * Format: date
             * @description ISO-8601 date (YYYY-MM-DD)
             * @example 2026-04-17
             */
            date: string;
            notes?: string | null;
            loggedFoods?: components["schemas"]["LoggedFoodDto"][];
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        /**
         * @description All locally-changed records since the last successful push.
         *     Any domain list may be omitted or empty — only changed records need to be sent.
         *     The server upserts by `serverId` using last-write-wins on `updatedAt`.
         */
        SyncPushRequest: {
            /** @default [] */
            foods: components["schemas"]["FoodDto"][];
            /** @default [] */
            meals: components["schemas"]["MealDto"][];
            /** @default [] */
            diets: components["schemas"]["DietDto"][];
            /** @default [] */
            healthMetrics: components["schemas"]["HealthMetricDto"][];
            /** @default [] */
            groceryLists: components["schemas"]["GroceryListDto"][];
            /** @default [] */
            dailyLogs: components["schemas"]["DailyLogDto"][];
        };
        SyncPushResponse: {
            /** @description Total number of records upserted across all domains */
            accepted: number;
        };
        /**
         * @description Delta payload — only records with `updatedAt > since` are included.
         *     Store `serverTime` locally and use it as `since` on the next pull to avoid gaps.
         */
        SyncPullResponse: {
            foods: components["schemas"]["FoodDto"][];
            meals: components["schemas"]["MealDto"][];
            diets: components["schemas"]["DietDto"][];
            healthMetrics: components["schemas"]["HealthMetricDto"][];
            groceryLists: components["schemas"]["GroceryListDto"][];
            dailyLogs: components["schemas"]["DailyLogDto"][];
            /**
             * Format: date-time
             * @description Server clock at the moment of this response — use as `since` on next pull
             */
            serverTime: string;
        };
    };
    responses: {
        /** @description Missing or invalid Firebase JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listFoods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of foods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodDto"];
            };
        };
        responses: {
            /** @description Created food */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFood: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Food */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFood: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMeals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of meals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createMeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealDto"];
            };
        };
        responses: {
            /** @description Created meal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDiets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of diets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDiet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DietDto"];
            };
        };
        responses: {
            /** @description Created diet */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDiet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDiet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGroceryLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of grocery lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroceryListDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGroceryList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroceryListDto"];
            };
        };
        responses: {
            /** @description Created grocery list */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroceryListDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGroceryList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grocery list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroceryListDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGroceryList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listHealthMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of health metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthMetricDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHealthMetric: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthMetricDto"];
            };
        };
        responses: {
            /** @description Created health metric */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthMetricDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteHealthMetric: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCustomMetricTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of custom types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomMetricTypeDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCustomMetricType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomMetricTypeDto"];
            };
        };
        responses: {
            /** @description Created custom type */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomMetricTypeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDailyLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of daily logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDailyLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyLogDto"];
            };
        };
        responses: {
            /** @description Created daily log */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDailyLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDailyLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    syncPull: {
        parameters: {
            query: {
                /** @description ISO-8601 instant — only records updated after this time are returned */
                since: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delta payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            /** @description Missing or malformed `since` parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Number of records accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
